[project]
name = "mini-inference-engine-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab>=4.5.3",
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "tqdm>=4.67.3",
]
